import type { Metadata } from "next";
import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/footer";
import DynamicHeader from "@/components/Header/DynamicHeader";

const urbanistSans = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanistSans.variable} ${geistMono.variable} antialiased`}>
        <DynamicHeader />
        <main className="bg-secondary min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
